language: python
python:
 - "3.5"
cache: pip
services:
  - postgresql
install:
 - pip install -r requirements.txt
 - pip install coveralls
before_sript:
   - psql -c 'create database test_db;' -U postgres
script:
 - pytest
after_success:
 - coveralls
  