language: python
python:
 - "3.5"
cache: pip
services:
  - postgresql
install:
 - pip install -r requirements.txt
 - pip install coveralls
before_script:
   - export SECRET="secret"
   - export DB_NAME="test_db"
   - export SECRET="a secret string of your choosing
   - psql -c 'create database test_db;' -U postgres
script:
 - pytest
 - pytest --cov=app
after_success:
 - coveralls
  